"""add email scan thread support and auto-discovery

Revision ID: e85755999482
Revises: asow3ktmv44e
Create Date: 2025-12-22 06:19:47.929886

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e85755999482"
down_revision: str | None = "asow3ktmv44e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deletion_requests",
        sa.Column("source", sa.String(), nullable=False, server_default="manual"),
    )
    op.add_column("email_scans", sa.Column("gmail_thread_id", sa.String(), nullable=True))
    op.add_column(
        "email_scans",
        sa.Column("email_direction", sa.String(), nullable=False, server_default="received"),
    )
    op.create_index(
        op.f("ix_email_scans_gmail_thread_id"), "email_scans", ["gmail_thread_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_scans_gmail_thread_id"), table_name="email_scans")
    op.drop_column("email_scans", "email_direction")
    op.drop_column("email_scans", "gmail_thread_id")
    op.drop_column("deletion_requests", "source")
    # ### end Alembic commands ###
